### ISSUE TITLE
Release version 1.3

### ISSUE THREAD

**Issue by linqcan** [xbmc/action-kodi-addon-submitter#12]
Version 1.2 contains linking to the wrong source repo of kodi-addon-submitter.

Please tag and release v1. 3, based on current master, to Github.

This is currently blocking all submissions using the Github action v1. 2.

@enen92 @romanvm

**Comment by enen92** [comment]
Dockerfile uses pip+git to pull the addon-submitter module: https://github.com/xbmc/action-kodi-addon-submitter/blob/master/Dockerfile#L7
While I think we should draft a new release anyway I don't see how this could be a hard requirement to get the action working again

**Comment by linqcan** [comment]
Log of issue here, you can see how it clones Roman's repo https://github.com/kodi-svtplay/xbmc-svtplay/runs/5852407562?check_suite_focus=true

**Comment by linqcan** [comment]
Thanks! 😊

**Comment by linqcan** [comment]
Thanks for fixing this @enen92! 🙏
