### ISSUE TITLE
Use GITHUB_TOKEN instead of GH_TOKEN

### ISSUE THREAD

**Issue by Razzeee** [xbmc/action-kodi-addon-submitter#7]
Is there any reason to use GH_TOKEN instead of GITHUB_TOKEN?

GITHUB_TOKEN seems to be available on every repo by default. It's at least documented here https://docs.github.com/en/free-pro-team@latest/actions/guides/publishing-nodejs-packages#publishing-packages-to-github-packages

**Comment by romanvm** [comment]
I wrote the original addon-submitter script for Travis CI because GitHub actions did not exist at that time. Hence the variable name. Also I'm not 100% that `GITHUB_TOKEN` has all necessary permissions for opening a PR, but this needs to be checked.

**Comment by michaelarnauts** [comment]
`GH_TOKEN` is a token for the actual user, so the PR will we opened as that user (the maintainer of the Add-on) while `GITHUB_TOKEN` seems to be a token for a **Github Actions** user.

Using `GITHUB_TOKEN` will have all PR's be opened as that **Github Actions** user.

**Comment by Razzeee** [comment]
I'm going to close this, as I'm not feeling like it's worth to investigate this further.
